INSERT INTO mahasiswa(id,npm,nama)
VALUES (1,'ade supri'),
		 (2'rivl supri'),
		 (3'der supri'),
		  (4'gestut supri'),
		  (5'bgg supri'),
		  (6'budi supri'),
		  (7'budi supri'),
		  (8'budi supri'),
		  (9'budi supri'),
		  (10'budi supri')
		  (11,'budi supri'),
		 (12'budi supri'),
		 (13'budi supri'),
		  (14'budi supri'),
		  (15'budi supri'),
		  (16'budi supri'),
		  (17'budi supri'),
		  (18'budi supri'),
		  (19'budi supri'),
		  (20'budi supri')